@GymManagement_HostAddress = http://localhost:5021
@AdminId = f1b570ad-ab00-4116-ae59-29d7c7b5582c

POST {{GymManagement_HostAddress}}/api/subscription/
Content-Type: application/json
{
  "SubscriptionType": "Pro",
  "AdminId": "{{AdminId}}"
}
###
